name: Application CI/CD pipeline

#trigger
on:
    push:
     branches:
       - 'main'
       - 'staging'
       - 'feature/**'

jobs:
  #specify Runner details:Self-hosted or GitHub Runner
  runs-on: "ubuntu-24.04"

  steps:
   - name: Clone repo
     uses: actions/checkout@v4

  - name: Build image
     run: docker build -t reviews-app-backend:0.1 .
     working-directory: ./api-backend

     
