name: Application CI/CD pipeline

# Trigger
on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'feature/**'

jobs:
  app-deploy: 
    #specify Runner details: Self-hosted or GitHub runner
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-regions: us-east-1
          role-to-assume: arn:aws:iam::025066251388:role/github-actions-cicd-role-dev
          role-session-name: gha-terraform-session


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: reviews-app-backend
          IMAGE_TAG: 0.1
        working-directory: ./api-backend
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG 
           #${{ steps.login-ecr.outputs.registry}} = 025066251388.dkr.ecr.us-east-1.amazonaws.com

      
     